name: heph_tf
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - alembic=1.17.1
  - bibtexparser=1.4.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorlog=6.10.1
  - contourpy=1.3.2
  - cuda-cccl_win-64=13.0.85
  - cuda-cudart-dev_win-64=13.0.96
  - cuda-cudart-static_win-64=13.0.96
  - cuda-cudart_win-64=13.0.96
  - cuda-nvrtc=13.0.88
  - cuda-version=13.0
  - cupy=13.6.0
  - cupy-core=13.6.0
  - cycler=0.12.1
  - dnspython=2.7.0
  - fastrlock=0.8.3
  - fonttools=4.58.0
  - freetype=2.13.3
  - future=1.0.0
  - gputil=1.4.0
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - joblib=1.5.1
  - latexcodec=2.0.1
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=13.1.0.3
  - libcufft=12.0.0.61
  - libcurand=10.4.0.35
  - libcusolver=12.0.4.66
  - libcusparse=12.6.3.3
  - libdeflate=1.24
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnvjitlink=13.0.88
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lxml=5.4.0
  - mako=1.3.10
  - matminer=0.9.3
  - matplotlib-base=3.10.3
  - mkl=2024.2.2
  - monty=2025.3.3
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=1.40.0
  - networkx=3.4.2
  - numba=0.61.2
  - openjpeg=2.5.3
  - openssl=3.5.4
  - optuna=3.6.1
  - packaging=25.0
  - palettable=3.3.3
  - pandas=2.2.3
  - pillow=11.2.1
  - pip=25.1
  - plotly=6.1.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pybtex=0.24.0
  - pycparser=2.22
  - pymatgen=2025.5.2
  - pymongo=4.11
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - requests=2.32.3
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.7.2
  - setuptools=78.1.1
  - shap=0.47.2
  - six=1.17.0
  - slicer=0.0.8
  - sniffio=1.3.1
  - spglib=2.6.0
  - sqlite=3.45.3
  - sympy=1.14.0
  - tabulate=0.9.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.3.0
  - tqdm=4.67.1
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - uncertainties=3.2.3
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - deprecated==1.2.18
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.2
      - grpcio==1.71.0
      - h5py==3.13.0
      - keras==3.10.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mendeleev==1.0.0
      - ml-dtypes==0.5.1
      - namex==0.0.9
      - numpy==1.26.4
      - nvidia-ml-py==13.580.82
      - opt-einsum==3.4.0
      - optree==0.15.0
      - optuna-integration==4.5.0
      - protobuf==5.29.4
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pyfiglet==0.8.post1
      - pygments==2.19.1
      - pynvml==13.0.1
      - rich==14.0.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sqlalchemy==2.0.41
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - typing-inspection==0.4.1
      - uuid==1.30
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xgboost==3.0.2
prefix: C:\Anaconda\envs\heph_tf
